### ISSUE TITLE
Can`t create custom stucture island

### ISSUE THREAD

**Issue by unsky555** [illyria-io/SkyblockX#19]
config.json fragment
`"islandMenuGUITitle": "Island Menu",
  "islandMenuGUIRows": 3,
  "islandMenuGUIBackgroundItem": {
    "material": "GRAY_STAINED_GLASS_PANE",
    "name": "&9",
    "lore": [
      ""
    ],
    "amt": 1
  },
  "islandMenuGUIItems": [
    {
      "guiItem": {
        "material": "GRASS_BLOCK",
        "name": "&bGo to island",
        "lore": [
          "&7Click to go to island"
        ],
        "amt": 1
      },
      "commandsToExecute": [
        "is go"
      ],
      "slot": 10
    },
    {
      "guiItem": {
        "material": "BOOK",
        "name": "&bIsland Quests",
        "lore": [
          "&7Click to open quests"
        ],
        "amt": 1
      },
      "commandsToExecute": [
        "is quest"
      ],
      "slot": 13
    },
    {
      "guiItem": {
        "material": "PLAYER_HEAD",
        "name": "&bManage Members",
        "lore": [
          "&7Click to manage island members"
        ],
        "amt": 1
      },
      "commandsToExecute": [
        "is members"
      ],
      "slot": 16
    }
  ],
  "islandCreateGUITitle": "Choose an island!",
  "islandCreateGUIRows": 1,
  "islandCreateGUIBackgroundItem": {
    "material": "BLACK_STAINED_GLASS_PANE",
    "name": "&9",
    "lore": [
      ""
    ],
    "amt": 1
  },
  "islandCreateGUIIslandTypes": [
    {
      "name": "normal",
      "requirementPermission": "skyblockx.islands.default",
      "guiIndex": 2,
      "item": {
        "material": "GRASS_BLOCK",
        "name": "&aBasic Island",
        "lore": [
          "&aThis is the basic starter island",
          "&aComes with everything you need to get started."
        ],
        "amt": 1
      },
      "structureFile": "island.structure",
      "netherFile": "nether-island.structure"
    },
    {
      "name": "classic",
      "requirementPermission": "skyblockx.islands.default",
      "guiIndex": 4,
      "item": {
        "material": "GOLD_BLOCK",
        "name": "&aS Island",
        "lore": [
          "&aThis is the basic starter island",
          "&aComes with everything you need to get started."
        ],
        "amt": 1
      },
      "structureFile": "classic.structure",
      "netherFile": "nether-island.structure"
    }
  ]`

**Console**

```

[12:32:01] [Server thread/INFO]: unsky issued server command: /is create
[12:32:03] [Server thread/ERROR]: Could not pass event InventoryClickEvent to SkyblockX vv1.3.6-alpha
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[server1.15.jar:git-Bukkit-61d4b09]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server1.15.jar:git-Bukkit-61d4b09]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:528) ~[server1.15.jar:git-Bukkit-61d4b09]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[server1.15.jar:git-Bukkit-61d4b09]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2087) ~[server1.15.jar:git-Bukkit-61d4b09]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[server1.15.jar:git-Bukkit-61d4b09]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[server1.15.jar:git-Bukkit-61d4b09]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[server1.15.jar:git-Bukkit-61d4b09]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [server1.15.jar:git-Bukkit-61d4b09]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [server1.15.jar:git-Bukkit-61d4b09]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [server1.15.jar:git-Bukkit-61d4b09]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [server1.15.jar:git-Bukkit-61d4b09]
        at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:875) [server1.15.jar:git-Bukkit-61d4b09]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:868) [server1.15.jar:git-Bukkit-61d4b09]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [server1.15.jar:git-Bukkit-61d4b09]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:852) [server1.15.jar:git-Bukkit-61d4b09]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:792) [server1.15.jar:git-Bukkit-61d4b09]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.IllegalArgumentException: No enum constant io.illyria.skyblockx.shade.baseplugin.XMaterial.Optional[Air]
        at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_211]
        at io.illyria.skyblockx.shade.baseplugin.XMaterial.valueOf(XMaterial.java:65) ~[?:?]
        at io.illyria.skyblockx.sedit.SkyblockEdit.pasteStructure(SkyblockEdit.kt:119) ~[?:?]
        at io.illyria.skyblockx.sedit.SkyblockEdit.pasteIsland(SkyblockEdit.kt:108) ~[?:?]
        at io.illyria.skyblockx.core.IslandKt.createIsland(Island.kt:464) ~[?:?]
        at io.illyria.skyblockx.core.IslandKt.createIsland$default(Island.kt:456) ~[?:?]
        at io.illyria.skyblockx.gui.IslandCreateGUI$populatePane$1.accept(IslandCreateGUI.kt:26) ~[?:?]
        at io.illyria.skyblockx.gui.IslandCreateGUI$populatePane$1.accept(IslandCreateGUI.kt:12) ~[?:?]
        at io.illyria.skyblockx.shade.stefvanschie.inventoryframework.pane.OutlinePane.click(OutlinePane.java:253) ~[?:?]
        at io.illyria.skyblockx.shade.stefvanschie.inventoryframework.pane.PaginatedPane.click(PaginatedPane.java:252) ~[?:?]
        at io.illyria.skyblockx.shade.stefvanschie.inventoryframework.GuiListener.onInventoryClick(GuiListener.java:77) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server1.15.jar:git-Bukkit-61d4b09]
        ... 17 more
```

**Comment by unsky559** [comment]
`Caused by: java.lang.IllegalArgumentException: No enum constant io.illyria.skyblockx.shade.baseplugin.XMaterial.Optional[Air]` this string is the way to understand the problem. SBFReader can not read the string `Optional[Air]`, it need to actualy be `AIR`. So to slove this I create another class that use SBFReader and SBFWriter to translate all wrong syntax to right, and it actually help. 
You need to add some checks in `SkyblockX/src/main/kotlin/io/illyria/skyblockx/sedit/SkyblockEdit.kt` before line 77. 
`XMaterial.matchXMaterial(block.type.name).toString()` - command returning to us `Optional[Air]`, so I just use this regex to check `(Optional|optional)\[(\w+\s\w+|\w+)]`, and after that make some string transform:
- to upper case
- all spaces replace with underscores
- remove Optional and square brackets

**Comment by unsky559** [comment]
`Caused by: java.lang.IllegalArgumentException: No enum constant io.illyria.skyblockx.shade.baseplugin.XMaterial.Optional[Air]` this string is the way to understand the problem. SBFReader can not read the string `Optional[Air]`, it need to actualy be `AIR`. So to slove this I create another class that use SBFReader and SBFWriter to translate all wrong syntax to right, and it actually help. 
@ProSavage, You need to add some checks in `SkyblockX/src/main/kotlin/io/illyria/skyblockx/sedit/SkyblockEdit.kt` before line 77. 
`XMaterial.matchXMaterial(block.type.name).toString()` - command returning to us `Optional[Air]`, so I just use this regex to check `(Optional|optional)\[(\w+\s\w+|\w+)]`, and after that make some string transform:
- to upper case
- all spaces replace with underscores
- remove Optional and square brackets
