### ISSUE TITLE
Some border errors

### ISSUE THREAD

**Issue by unsky559** [illyria-io/SkyblockX#43]
I download last build from your [website](https://dl.savagelabs.net/plugins) called `skyblockx-1160.jar`. So, when I go to my island, there is border errors in console and also border does not work

```
[00:54:17] [Server thread/WARN]: java.lang.NullPointerException
[00:54:17] [Server thread/WARN]:        at net.savagelabs.skyblockx.shade.baseplugin.WorldBorderUtil.sendWorldBorder(WorldBorderUtil.java:60)
[00:54:17] [Server thread/WARN]:        at net.savagelabs.skyblockx.core.UtilKt$updateWorldBorder$1.run(Util.kt:54)
[00:54:17] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:77)
[00:54:17] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:393)
[00:54:17] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:979)
[00:54:17] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:380)
[00:54:17] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:934)
[00:54:17] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:788)
[00:54:17] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)

```

**Comment by prosavage** [comment]
Run /is border and change it once and see if it still happens.
